#!/bin/sh

ACCENT=../accent/accent
ENTIRE=../entire/entire.c
LEX=lex
CC=cc

$ACCENT spec.acc

$LEX spec.lex

$CC -o relational-algebra lex.yy.c auxil.c yygrammar.c $ENTIRE -w

relational-algebra < input
