SIGMA Dnr=4 (FUNCIONARIO)
SIGMA Salario>30000 (FUNCIONARIO)
SIGMA (Dnr=4 AND Salario>25000) OR (Dnr=5 AND Salario>30000)(FUNCIONARIO)
SIGMA Dnr=4 (SIGMA Salario< 10000 (SIGMA idade > 18 (FUNCIONARIO)))
SIGMA Dnr=4 AND Salario>25000 (FUNCIONARIO)

PI Unome, Pnome, Salario (FUNCIONARIO)
PI Sexo, Salario (FUNCIONARIO)
PI Pnome, Unome, Salario (SIGMA Dnr=5 (FUNCIONARIO))

FUNCS_DEPT5 ATRIBUICAO SIGMA Dnr=5(FUNCIONARIO)
RESULTADO1 ATRIBUICAO PI Cpf(FUNCS_DEPT5)
RESULTADO2 ATRIBUICAO PI Cpf_supervisor(FUNCS_DEPT5)
RESULTADO ATRIBUICAO RESULTADO1 UNIAO RESULTADO2
RHO FUNCS_DEPT5 (SIGMA Dnr=5(FUNCIONARIO))

FUNC_MULHERES ATRIBUICAO SIGMA Sexo='F'(FUNCIONARIO)
FUNCNOMES ATRIBUICAO PI Pnome,Unome,Cpf(FUNC_MULHERES)
FUNC_DEPENDENTES ATRIBUICAO FUNCNOMES PRODUTO_CARTESIANO DEPENDENTE
DEPENDENTE_PARTIC ATRIBUICAO SIGMA Cpf=Fcpf(FUNC_DEPENDENTES)
DEPENDENTE_PARTIC ATRIBUICAO FUNCNOMES JUNCAO Cpf=Fcpf DEPENDENTE
RESULTADO ATRIBUICAO PI Pnome, Unome, Nome_dependente(DEPENDENTE_PARTIC)

DEP_GER ATRIBUICAO DEPARTAMENTO JUNCAO Cpf_gerente=Cpf FUNCIONARIO
RESULTADO ATRIBUICAO PI Dnome, Unome, Pnome (DEP_GER)

PROJETO_DEP ATRIBUICAO PROJETO JUNCAO_NATURAL RHO (Dnome, Dnum, Cpf_gerente, Data_inicio_gerente)(DEPARTAMENTO)
DEP ATRIBUICAO RHO(Dnome, Dnum, Cpf_gerente, Data_inicio_gerente)(DEPARTAMENTO)
PROJETO_DEP ATRIBUICAO PROJETO JUNCAO_NATURAL DEP
LOCAL_DEP ATRIBUICAO DEPARTAMENTO JUNCAO_NATURAL LOCALIZACAO_DEP

((PROJETO JUNCAO Dnum=Dnumero DEPARTAMENTO) JUNCAO Cpf_gerente=Cpf FUNCIONARIO)

SILVA ATRIBUICAO SIGMA Pnome='Joao' AND Unome='Silva' (FUNCIONARIO)
SILVA_PNRS ATRIBUICAO PI Pnr (TRABALHA_EM JUNCAO Fcpf=Cpf SILVA)
CPF_PNRS ATRIBUICAO PI Fcpf,Pnr (TRABALHA_EM)
CPFS ATRIBUICAO CPF_PNRS DIVISAO SILVA_PNRS
RESULTADO ATRIBUICAO PI Pnome, Unome (CPFS JUNCAO_NATURAL FUNCIONARIO)

RELATORIO ATRIBUICAO RHO (Cpf, Salario_liquido, Bonus, Imposto) (PI Cpf, Salario - Deducao, 2000 * Anos_em_servico, 0.25 * Salario (FUNCIONARIO))

RHO R (Dnr, Nr_de_funcionarios, Media_sal) (Dnr FSCRIPT COUNT Cpf, AVERAGE Salario (FUNCIONARIO))

/* OPERACOES DE FECHAMENTO RECURSIVO */
CPF_BRITO ATRIBUICAO PI Cpf( SIGMA Pnome='Jorge' AND Unome='Brito' (FUNCIONARIO))
SUPERVISAO(Cpf1, Cpf2) ATRIBUICAO PI Cpf,Cpf_supervisor (FUNCIONARIO)
RESULTADO1(Cpf) ATRIBUICAO PI Cpf1 (SUPERVISAO JUNCAO Cpf2=Cpf CPF_BRITO)
RESULTADO2(Cpf) ATRIBUICAO PI Cpf1 (SUPERVISAO JUNCAO Cpf2=Cpf RESULTADO1)
RESULTADO ATRIBUICAO RESULTADO2 UNIAO RESULTADO1

/* OPERACOES DE JUNÇÃO EXTERNA */
TEMP ATRIBUICAO (FUNCIONARIO JUNCAO_EXTERNA_ESQUERDA Cpf=Cpf_gerente DEPARTAMENTO)
RESULTADO ATRIBUICAO PI Pnome, Minicial, Unome, Dnome (TEMP)

/* EXEMPLOS DE CONSULTAS DA SEÇÃO 6.5  */

/*Consulta 1: Recuperar o nome e o endereço de todos os funcionários que trabalham para o departamento 'Pesquisa'*/
DEP_PESQUISA ATRIBUICAO SIGMA Dnome='Pesquisa' (DEPARTAMENTO)
FUNCS_PESQUISA ATRIBUICAO (DEP_PESQUISA JUNCAO Dnumero=Dnr FUNCIONARIO)
RESULTADO ATRIBUICAO PI Pnome,Unome,Endereco (FUNCS_PESQUISA)

/*Consulta 1 em uma única linha*/
PI Pnome,Unome,Endereco (SIGMA Dnome='Pesquisa' (DEPARTAMENTO JUNCAO Dnumero=Dnr (FUNCIONARIO)))

/*Consulta 2: Para cada projeto localizado em 'Mauá', liste o número do projeto, o número do departamento que o controla e o último nome, endereço e data de nascimento do gerente do departamento*/
PROJ_MAUA ATRIBUICAO SIGMA Projlocal='Mauá' (PROJETO)
DEP_CONTROLE ATRIBUICAO (PROJ_MAUA JUNCAO Dnum=Dnumero DEPARTAMENTO)
GER_DEP_PROJ ATRIBUICAO (DEP_CONTROLE JUNCAO Cpf_gerente=Cpf FUNCIONARIO)
RESULTADO ATRIBUICAO PI Projnumero, Dnum, Unome, Endereco, Datanasc (GER_DEP_PROJ)

/*Consulta 3: Descobrir os nomes dos funcionários que trabalham em todos os projeto controlados pelo departamento número 5.*/
PROJ_DEP5 ATRIBUICAO RHO(Pnr) (PI Projnumero (SIGMA Dnum=5 (PROJETO)))
FUNC_PROJ ATRIBUICAO RHO (Cpf, Pnr) (PI Fcpf, Pnr (TRABALHA_EM))
RESULTADO_CPF_FUNC ATRIBUICAO FUNC_PROJ DIVISAO PROJ_DEP5 /* Atributos foram renomeados para serem utilizados na operação de divisão*/
RESULTADO ATRIBUICAO PI Unome, Pnome (RESULTADO_CPF_FUNC JUNCAO_NATURAL FUNCIONARIO) 

/*Consulta 4: Fazer uma lista dos números de projeto para aqueles que envolvem um funcionário cujo último nome é 'Silva', seja como um trabalhador ou como um gerente do departamento que controla o projeto.*/
SILVA(Fcpf) ATRIBUICAO PI Cpf ( SIGMA Unome='Silva' (FUNCIONARIO))
PROJ_SILVA_TRAB ATRIBUICAO PI Pnr (TRABALHA_EM JUNCAO_NATURAL SILVA)
GERENTES ATRIBUICAO PI Unome, Dnumero ( FUNCIONARIO JUNCAO Cpf=Cpf_gerente DEPARTAMENTO)
DEPS_GERENCIADOS_SILVA(Dnum) ATRIBUICAO PI Dnumero ( SIGMA Unome='Silva' (GERENTES))
PROJS_SILVA_GER(Pnr) ATRIBUICAO PI Projnumero (DEPS_GERENCIADOS_SILVA JUNCAO_NATURAL PROJETO)
RESULTADO ATRIBUICAO (PROJ_SILVA_TRAB UNIAO PROJS_SILVA_GER)

/*Consulta 4 em uma única linha.*/
PI Pnr (TRABALHA_EM JUNCAO Fcpf=Cpf (PI Cpf (SIGMA Unome='Silva' (FUNCIONARIO))) UNIAO PI Pnr ((PI Dnumero (SIGMA Unome='Silva' (PI Unome,Dnumero (FUNCIONARIO))) JUNCAO Cpf=Cpf_gerente DEPARTAMENTO)) JUNCAO Dnumero=Dnum PROJETO)

/*Consulta 5: Listar os nomes de todos os funcionários com dois ou mais dependentes.*/
T1(Cpf,Nr_de_dependentes) ATRIBUICAO Fcpf FSCRIPT COUNT Nome_dependente (DEPENDENTE)
T2 ATRIBUICAO SIGMA Nr_de_dependentes>2 (T1)
RESULTADO ATRIBUICAO PI Unome, Pnome ( T2 JUNCAO_NATURAL FUNCIONARIO)

/*Consulta 6: Recuperar os nomes dos funcionários que não possuem dependentes. Exemplo de uso da operação SUBTRACAO*/
TODOS_FUNCS ATRIBUICAO PI Cpf (FUNCIONARIO)
FUNCS_COM_DEPEND(Cpf) ATRIBUICAO PI Fcpf (DEPENDENTE)
FUNCS_SEM_DEPEND ATRIBUICAO (TODOS_FUNCS SUBTRACAO FUNCS_COM_DEPEND)
RESULTADO ATRIBUICAO PI Unome, Pnome (FUNCS_SEM_DEPEND JUNCAO_NATURAL FUNCIONARIO)

/*Consulta 6 em apenas uma expressão */
PI Unome,Pnome ((PI Cpf (FUNCIONARIO) SUBTRACAO RHO Cpf (PI Fcpf (DEPENDENTE))) JUNCAO_NATURAL FUNCIONARIO)

/*Consulta 7: Listar os nomes dos gerentes que têm pelo menos um dependente.*/
GERS(Cpf) ATRIBUICAO PI Cpf_gerente(DEPARTAMENTO)
FUNCS_COM_DEPEND(Cpf) ATRIBUICAO PI Fcpf (DEPENDENTE)
GER_COM_DEPEND ATRIBUICAO ( GERS INTERSECCAO FUNCS_COM_DEPEND)
RESULTADO ATRIBUICAO PI Unome, Pnome (GERS_COM_DEPEND JUNCAO_NATURAL FUNCIONARIO)



